bundler_args: --binstubs

rvm:
  - 1.9.3
  - 1.8.7
  - ree

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ree

script: "bundle exec rspec spec"

notifications:
  recipients:
    - markmulder@gmail.com

branches:
  only:
    - master

